### ISSUE TITLE
How to just get the value dirctly without using any String methods?

### ISSUE THREAD

**Issue by DevAloshe** [point-source/dart_snmp#18]
I'm getting this results when I use this code :
```dart
import 'dart:io';
import 'package:dart_snmp/dart_snmp.dart';
import 'package:dart_snmp/src/models/varbind.dart';

void main() async {
  // Starting a session
  var target = InternetAddress('192.168.1.1');
  var session = await Snmp.createSession(target);

  // Reading a parameter
  var oid = Oid.fromString('1.3.6.1.4.1.43356.2.1.2.1.4.0'); // sysDesc
  var message = await session.get(oid);
  print(message.pdu.varbinds[0]); // outputs system description

  // Writing a parameter
  var varbind = Varbind(
    oid,
    VarbindType.OctetString,
    'New system description',
  ); // create payload
  await session.set(varbind); // send new system description to target
}
```
Results : 

`flutter: 1.3.6.1.4.1.43356.2.1.2.1.4.0 = OctetString: 2018-06-02 00:23:04 (UTC +0000)`

I just want to get the value :  `2018-06-02 00:23:04 (UTC +0000)` without using any `String Methods`
is that possible ?
thanks for your great package 💯

**Comment by point-source** [comment]
No problem! Just modify your print statement to reference the `value` of the varbind object:
` print(message.pdu.varbinds[0].value); // outputs system description`

**Comment by DevAloshe** [comment]
it worked (: thank you so much, btw I tried to do this before and the `chatGPT ` told me to add `.value` but I don't know why it didn't work before .

there is another issue if you don't mind sir : 
how to to send one snmp call to get multiple results like when I want to get the `sysdesc,deviceName,time,..etc`
I know about `getBulk `but I think it doesn't support specifying the `Oids` that I just needed to get them
is there a way to make one SNMP call and  pass the `Oids ` I just needed ?
thank you for your response .
