### ISSUE TITLE
Set BITS type

### ISSUE THREAD

**Issue by darlisonosorio** [point-source/dart_snmp#3]
Hi.

Do you have any example of how to send a SET for BITS type?

**Comment by point-source** [comment]
I'm not familiar with BITS type. Can you give me a bit more context or an example? Is this specific to a type or model of equipment?

**Comment by darlisonosorio** [comment]
This link has more details about BITS type:
https://www.webnms.com/snmp/help/snmpapi/snmpv3/using_mibs_in_applns/bits_datatype.html

In resume, its a byte value where every digit represents an option and 0 or 1 is true or false for it.

I'm having problems to set the variable, It says I have to save as OCTET STRING, but I don't know how to format the value.
I tried to save as byte (0101010), as hex (0x42), as UTF8 (B). It always says "wrong length".

**Comment by point-source** [comment]
You should be able to do it like this:

```dart
void main() async {
  var target = InternetAddress('192.168.1.1');
  var session = await Snmp.createSession(target);
  var varbind = Varbind(
    Oid.fromString('1.3.6.1.2.1.1.1.0'), // which oid should we be setting?
    VarbindType.OctetString, // BITS is a psudo-type which is encoded as an Octet String
    Uint8List.fromList([0x64]), // This is the data we are encoding. 0x64 is from the example you linked
  );
  var result = await session.set(varbind); // send a set command to the target with the varbind payload
}

```

Note that the oid in the example is not valid for this pupose.

**Comment by darlisonosorio** [comment]
It worked for me.
Thank you so much.
