### ISSUE TITLE
Unhandled Exception: Exception: Snmp Pdu Error on 1.3.6.1.2.1.1.5.0: WrongValue

### ISSUE THREAD

**Issue by blackangiliq** [point-source/dart_snmp#6]
Hi I have this problem when I try to send a new sysname to cisco via snmp using this command

It is already fetching the name, but when trying to set a name, it throws this error

and in the end thanx for this lib 

> 
> flutter: INFO: 2022-01-30 04:47:48.265034: Snmp v2c session initialized.
> flutter: INFO: 2022-01-30 04:47:48.284396: Bound to target 0.0.0.0 on port 56504
> 
> flutter: 1.3.6.1.2.1.1.5.0 = OctetString: hellow
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
> #0      _AsyncCompleter.complete (dart:async/future_impl.dart:45:31)
> #1      Request.complete (package:dart_snmp/src/models/request.dart:45:15)
> #2      Snmp._onEvent (package:dart_snmp/src/snmp_base.dart:153:36)
> #3      _rootRunUnary (dart:async/zone.dart:1444:13)
> #4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
> #9      _StreamController._add (dart:async/stream_controller.dart:607:7)
> #10     _StreamController.add (dart:async/stream_controller.dart:554:5)
> #11     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2391:33)
> #12     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
> #13     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Snmp Pdu Error on 1.3.6.1.2.1.1.5.0: WrongValue
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
> #0      _Completer.completeError (dart:async/future_impl.dart:24:31)
> #1      Request.completeError (package:dart_snmp/src/models/request.dart:49:49)
> #2      Request.complete (package:dart_snmp/src/models/request.dart:42:7)
> #3      Snmp._onEvent (package:dart_snmp/src/snmp_base.dart:153:36)
> #4      _rootRunUnary (dart:async/zone.dart:1444:13)
> #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
> #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
> #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
> #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> #9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
> #10     _StreamController._add (dart:async/stream_controller.dart:607:7)
> #11     _StreamController.add (dart:async/stream_controller.dart:554:5)
> #12     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2391:33)
> #13     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1314:14)
> #14     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> 
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: Future already completed
> #0      _Completer.completeError (dart:async/future_impl.dart:24:31)
> #1      Request.completeError (package:dart_snmp/src/models/request.dart:49:49)
> #2      Snmp._timeout (package:dart_snmp/src/snmp_base.dart:277:11)
> #3      Snmp._send.<anonymous closure> (package:dart_snmp/src/snmp_base.dart:266:43)
> #4      new Future.delayed.<anonymous closure> (dart:async/future.dart:393:39)
> #5      _rootRun (dart:async/zone.dart:1420:47)
> #6      _CustomZone.run (dart:async/zone.dart:1328:19)
> #7      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
> #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
> #9      _rootRun (dart:async/zone.dart:1428:13)
> #10     _CustomZone.run (dart:async/zone.dart:1328:19)
> #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
> #12     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
> #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
> #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
> #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
> 
> 

my code down blew 

where i gone wrong ?

```dart
var target = InternetAddress('192.168.1.2');
  var session = await Snmp.createSession(target,port: 161 , community: "private");
  var oid = Oid.fromString('1.3.6.1.2.1.1.5.0');
  // sysDesc
  var message = await session.get(oid);


  print(message.pdu.varbinds[0]); // outputs system description


  var varbind = Varbind(
oid,
    VarbindType.OctetString,
    'New system description',
  ); // create payload
  await session.set(varbind);
```

**Comment by blackangiliq** [comment]
thanx i fix it :)



with this 



import 'dart:io';
import 'package:dart_snmp/dart_snmp.dart';
import 'package:dart_snmp/src/models/varbind.dart';
import 'package:flutter/material.dart';


void main() async {

  runApp(runa());
}


class runa extends StatefulWidget {
  @override
  _runaState createState() => _runaState();
}

class _runaState extends State<runa> {

  @override
  void initState() {
    // TODO: implement initState
    Getname();
  }
  var theoldname;
  void Getname
      ()async{


    var target = InternetAddress('192.168.1.2');
    var session = await Snmp.createSession(target,port: 161 , community: "private" ,);
    var oid = Oid.fromString('1.3.6.1.2.1.1.5.0');
    // sysDesc
    var message = await session.get(oid);


    print(message.pdu.varbinds[0]); // outputs system description
theoldname = message.pdu.varbinds[0];

  var varbind = Varbind(
oid,
    VarbindType.OctetString,
    'New',
  ); // create payload
    var message2 =   await session.set(varbind,target: target , port: 161);

  }
  void Fucnrename()async{


    var target = InternetAddress('192.168.1.2');
    var session = await Snmp.createSession(target,port: 161 , community: "private" ,);
    var oid = Oid.fromString('1.3.6.1.2.1.1.5.0');
    // sysDesc
    var message = await session.set("1.3.6.1.2.1.1.5.0 = OctetString: black" as Varbind);


    print(message.pdu.varbinds[0]); // outputs system description


//   var varbind = Varbind(
// oid,
//     VarbindType.OctetString,
//     'New system description',
//   ); // create payload
    var message2 =   await session.set(message.pdu.varbinds[0]);

  }
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body:
        Center(
          child:
     RaisedButton(onPressed: (){
       Fucnrename();
     })
          ,
        ),
      ),
    );
  }
}

**Comment by point-source** [comment]
Not sure I completely understand your fix but if you have it working, can I close this PR?

**Comment by blackangiliq** [comment]
sure u can but i have another issue :(

**Comment by blackangiliq** [comment]
thnx

**Comment by point-source** [comment]
> sure u can but i have another issue :( 
> 
> 

What is the other issue?
