### ISSUE TITLE
Can I get router arp table using this package

### ISSUE THREAD

**Issue by guyluz11** [point-source/dart_snmp#8]
Is there a way to get the router [arp](https://en.wikipedia.org/wiki/Address_Resolution_Protocol) table using this package?.

**Comment by point-source** [comment]
Yes, you are able to do that but table data is spread across multiple OIDs so you'd have to get each OID or walk/getbulk them all and then reconstruct the table yourself. This library does not automatically parse/format tables but it can return all necessary data to do so.

**Comment by guyluz11** [comment]
I think my router does not support snmp so I can't try it out in my package.

Thank you for your answer :)
