### ISSUE TITLE
asn1lib >=1.20 fails to decode snmp message sequences (tag 162) which causes dart_snmp to timeout

### ISSUE THREAD

**Issue by Siddhant-Kr-Singh** [point-source/dart_snmp#9]
Hi there,
I am facing a request time out issue. Below is the code I am using
```
    var target = InternetAddress('192.168.0.1');
    var session = await Snmp.createSession(target);
    var oid = Oid.fromBytes(ASN1OctetString('1.3.6.1.2.1.1.1.0').encodedBytes);
    var message;
    try {
      message = await session.get(oid);
    } catch (e) {
      print(e);
    }

```
Output: 

```
    Snmp v2c session initialized.
    Bound to target 0.0.0.0 on port 52912
    Exception: Request to 192.168.0.1:161 timed out
```
When I try to connect with the same IP from the terminal I am able to get the data but not via flutter (dart_snmp).
What should I do to fix it ?

**Comment by Siddhant-Kr-Singh** [comment]
I am testing it on the **iOS simulator** and the Android physical device on **Debugging mode**.
When I am running the command on terminal **snmpget -v 2c -c public -On 192.168.0.1 1.3.6.1.2.1.1.1.0**, I am getting a vaild output, but using the above code; the output is request timeout exception

**Comment by point-source** [comment]
Correct. That's because the android device doesn't have the snmpwalk utility on it. So just ping it instead. `ping 192.168.0.1`

**Comment by Siddhant-Kr-Singh** [comment]
Yes,  I am able to ping. But I want to mine the data via SNMP. Does it package requires any additional software installation for that ?

**Comment by point-source** [comment]
I was just requesting that check to ensure that the android device had a valid route to the target device on the network. If you can ping it, then dart-snmp should work provided that your app has network permissions granted. No additional libraries needed. Dart-snmp constructs and interprets raw snmp packets by connecting to a socket.

**Comment by Siddhant-Kr-Singh** [comment]
The network permissions are granted to android and iOS devices, but can not find the actual reason why this is happening.
This is really urgent for my project

**Comment by Shivkant-Sisodiya** [comment]
Hi @point-source , I am also facing the same issue.

**Comment by Siddhant-Kr-Singh** [comment]
@point-source is there anything else, that you can help with. Because I am stuck at the same place

**Comment by point-source** [comment]
I will test it on my end. In the meantime, if you want to try just establishing a basic dart io Socket connection to the device on port 161 and send a packet, it will help eliminate issues.

**Comment by Siddhant-Kr-Singh** [comment]
I am already running a Socket connection(Web Socket) in the application

**Comment by point-source** [comment]
WebSocket is different. Need to use `Socket` from dart:io.

**Comment by Siddhant-Kr-Singh** [comment]
Hi @point-source can we connect if you are available, it's a humble request

**Comment by point-source** [comment]
Yes that's fine but I can't for probably an hour at least :(

**Comment by Siddhant-Kr-Singh** [comment]
Sure, lets connect after an hour, let say 1:30 A.M IST

**Comment by point-source** [comment]
I'm sorry, still working. I'm in PST so it's the middle of my workday. I haven't forgotten, just gotta prioritize the main thing over the OSS stuff. :(

**Comment by point-source** [comment]
I have reproduced the issue here and am investigating.

**Comment by point-source** [comment]
You can temporarily work around the issue by adding this to your pubspec.yaml:

```
dependency_overrides:
  asn1lib: 1.1.1
```

I will file a bug with the asn1lib developer

**Comment by Siddhant-Kr-Singh** [comment]
No issues.
I was trying but still stuck at the same issue, I think you should take a look once

**Comment by point-source** [comment]
Try updating your dependencies and let me know. The developer of the asn1lib has released an update.

**Comment by Siddhant-Kr-Singh** [comment]
Hi @point-source I did try
```
dependency_overrides:
  asn1lib: 1.1.1
```
But I am getting the same Request timed out exception.
After that I updated the dependencies and still same exception.

**Comment by point-source** [comment]
Try setting the timeout parameter to something higher than 5 seconds (the default) to see what the actual error is.

**Comment by Siddhant-Kr-Singh** [comment]
The timeout is set to 50 seconds and version of asn1lib is:
`asn1lib: ^1.2.2`

**Comment by point-source** [comment]
And even after that, the error is still a timeout? If so, please try to step back/into the stacktrace and locate the source of the error. I was able to reproduce the initial issue but it seems to be fixed for asn1lib 1.2.2 so far. Could you perhaps check to see if it is timing out while trying to decode a byte sequence or if it is truly failing to connect at all?

**Comment by Siddhant-Kr-Singh** [comment]
It is failing to connect to the target. But how come I am able to connect to the same target with my Terminal

**Comment by Siddhant-Kr-Singh** [comment]
I figured it out, the issue is resolved now. 
Instead of doing this
`var oid = Oid.fromBytes(ASN1OctetString('1.3.6.1.2.1.1.1.0').encodedBytes);`
